import numpy as np
import csv
import os

cwd = os.getcwd()

def loadMeshDataAIP(filepath):
    '''Loads mesh .dat files generated by FLITE and stores as lists'''
    
    fn1 = 'meshCoor.dat'
    file = open(f'{filepath}\\{fn1}', "r")
    meshCoor = np.loadtxt(file)
    
    fn2 = 'meshConnec.dat'
    file = open(f'{filepath}\\{fn2}', "r")
    meshCon = np.loadtxt(file)
    
    fn3 = 'meshBound.dat'
    file = open(f'{filepath}\\{fn3}', "r")
    meshBound = np.loadtxt(file)
    
    return meshCoor, meshCon, meshBound
   
    
def loadResidualData(filepath):
    '''Loads results .dat file generated by FLITE and stores as lists'''
    
    filename = 'residual.dat'
    file = open(f'{filepath}\\{filename}', "r")
    residual = np.loadtxt(file)
    
    return residual
    
    
def loadCoordinates(filepath, filename):
    '''Loads 2D xy or 3D xyz coordinates .csv file generated by parameterization code'''
    
    file = open(f'{filepath}\{filename}', "r")
    data = list(csv.reader(file, delimiter=","))
    file.close()
    
    return data

def loadGeometry(gen, agent):
    # Load intake xy coordinates
    filepath = cwd + r"\Outputs\Geometry Coordinates"
    directory = f"Generation {gen}"
    path = os.path.join(filepath, directory)
    cowlfilename = f"cowlGeometry{agent}.csv"
    rampfilename = f"rampGeometry{agent}.csv"
    xyCoordsCowl = loadCoordinates(path, cowlfilename)
    xyCoordsCone = loadCoordinates(path, rampfilename)

    xCoordsCowl = [float(row[0]) for row in xyCoordsCowl]
    yCoordsCowl = [float(row[1]) for row in xyCoordsCowl]
    xCoordsCowl.append(xCoordsCowl[0])
    yCoordsCowl.append(yCoordsCowl[0])

    xCoordsCone = [float(row[0]) for row in xyCoordsCone]
    yCoordsCone = [float(row[1]) for row in xyCoordsCone]
    xCoordsCone.append(xCoordsCone[0])
    yCoordsCone.append(yCoordsCone[0])

    return xCoordsCowl, yCoordsCowl, xCoordsCone, yCoordsCone 

def loadSurfaceCoords(filename):
    '''Loads the coordinates of a surface extracted from CAD file'''
    
    import vtk
    reader = vtk.vtkGenericDataObjectReader()
    reader.SetFileName(filename)
    reader.Update()

    points = np.array( reader.GetOutput().GetPoints().GetData() )
    return points


def loadControlNodes(directory):
    path = os.path.join(directory, "optimisationCN.txt")
    with open(path, "r") as file:
        data = [
            [float(value) for value in row if value.strip() != ""]
            for row in csv.reader(file, delimiter=" ")
        ]
    return data

def loadControlPoints(directory):
    path = os.path.join(directory, "surfaceControlPoints.txt")
    with open(path, "r") as file:
        data = [
            [float(value) for value in row if value.strip() != ""]
            for row in csv.reader(file, delimiter=" ")
        ]
    return data